services:
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=pass
      - MONGO_INITDB_DATABASE=auth

  mongo-express:
    image: mongo-express
    depends_on:
      - mongodb
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
      - ME_CONFIG_MONGODB_SERVER=mongodb
    ports:
      - '8081:8081'

  node-app:
    build: .
    environment:
      - PORT=3000
    volumes:
      - '.:/usr/src/code'
      - '/usr/src/code/node_modules'
    ports:
      - '3000:3000'
